// =============================================
// MOCK DATA - Medicines
// =============================================
export const medicines = [
  {
    id: "med-001",
    name: "Paracetamol 500mg",
    brand: "Dolo",
    category: "Pain Relief",
    price: 45,
    originalPrice: 60,
    rating: 4.8,
    reviews: 2341,
    inStock: true,
    prescriptionRequired: false,
    image: "/medicines/dolo.png",
    description: "Fast-acting pain relief and fever reducer",
    uses: ["Fever", "Headache", "Body pain", "Toothache"],
    dosage: "1-2 tablets every 4-6 hours. Max 8 tablets per day.",
    sideEffects: ["Nausea (rare)", "Rash (rare)", "Liver damage (overdose)"],
    warnings: ["Do not exceed recommended dose", "Consult doctor if symptoms persist >3 days"],
    manufacturer: "Micro Labs Ltd",
    expiryDate: "2026-12",
    composition: "Paracetamol 500mg",
  },
  {
    id: "med-002",
    name: "Cetirizine 10mg",
    brand: "Allegra",
    category: "Allergy",
    price: 85,
    originalPrice: 110,
    rating: 4.6,
    reviews: 1872,
    inStock: true,
    prescriptionRequired: false,
    image: "/medicines/allegra.png",
    description: "24-hour allergy relief antihistamine",
    uses: ["Hay fever", "Allergic rhinitis", "Urticaria", "Sneezing"],
    dosage: "1 tablet daily, preferably at bedtime",
    sideEffects: ["Drowsiness", "Dry mouth", "Headache"],
    warnings: ["May cause drowsiness", "Avoid alcohol", "Not for children under 6"],
    manufacturer: "Sanofi India",
    expiryDate: "2026-08",
    composition: "Cetirizine Hydrochloride 10mg",
  },
  {
    id: "med-003",
    name: "Omeprazole 20mg",
    brand: "Omez",
    category: "Acidity",
    price: 120,
    originalPrice: 150,
    rating: 4.7,
    reviews: 3201,
    inStock: true,
    prescriptionRequired: false,
    image: "/medicines/omez.png",
    description: "Proton pump inhibitor for acid reflux relief",
    uses: ["Acid reflux", "GERD", "Stomach ulcers", "Heartburn"],
    dosage: "1 capsule 30 min before meal, once daily",
    sideEffects: ["Headache", "Diarrhea", "Stomach pain"],
    warnings: ["Long-term use may cause magnesium deficiency", "Not for immediate relief"],
    manufacturer: "Dr. Reddy's Laboratories",
    expiryDate: "2027-03",
    composition: "Omeprazole 20mg",
  },
  {
    id: "med-004",
    name: "Vitamin D3 1000IU",
    brand: "SunD3",
    category: "Vitamins",
    price: 199,
    originalPrice: 250,
    rating: 4.9,
    reviews: 5621,
    inStock: true,
    prescriptionRequired: false,
    image: "/medicines/sund3.png",
    description: "Essential vitamin for bone and immune health",
    uses: ["Vitamin D deficiency", "Bone health", "Immune support", "Mood"],
    dosage: "1 tablet daily with food",
    sideEffects: ["Nausea (rare)", "Constipation (high doses)"],
    warnings: ["Consult doctor if taking other medications", "Don't exceed 4000IU/day"],
    manufacturer: "HealthKart",
    expiryDate: "2027-06",
    composition: "Cholecalciferol 1000IU",
  },
  {
    id: "med-005",
    name: "Azithromycin 500mg",
    brand: "Zithromax",
    category: "Antibiotic",
    price: 165,
    originalPrice: 200,
    rating: 4.5,
    reviews: 987,
    inStock: false,
    prescriptionRequired: true,
    image: "/medicines/blister.png",
    description: "Broad-spectrum antibiotic for bacterial infections",
    uses: ["Respiratory infections", "Skin infections", "Ear infections"],
    dosage: "1 tablet once daily for 3-5 days as prescribed",
    sideEffects: ["Nausea", "Diarrhea", "Abdominal pain", "QT prolongation"],
    warnings: ["Complete the full course", "Not for viral infections", "Prescription required"],
    manufacturer: "Pfizer",
    expiryDate: "2026-09",
    composition: "Azithromycin 500mg",
  },
  {
    id: "med-006",
    name: "Metformin 500mg",
    brand: "Glycomet",
    category: "Diabetes",
    price: 89,
    originalPrice: 120,
    rating: 4.7,
    reviews: 4521,
    inStock: true,
    prescriptionRequired: true,
    image: "/medicines/blister.png",
    description: "First-line medication for type 2 diabetes management",
    uses: ["Type 2 diabetes", "Pre-diabetes", "PCOS"],
    dosage: "1 tablet twice daily with meals as prescribed",
    sideEffects: ["Nausea", "Diarrhea", "Metallic taste", "Lactic acidosis (rare)"],
    warnings: ["Monitor kidney function", "Avoid alcohol", "Regular blood sugar monitoring"],
    manufacturer: "USV Ltd",
    expiryDate: "2026-11",
    composition: "Metformin Hydrochloride 500mg",
  },
  {
    id: "med-007",
    name: "Ibuprofen 400mg",
    brand: "Brufen",
    category: "Pain Relief",
    price: 55,
    originalPrice: 70,
    rating: 4.6,
    reviews: 2890,
    inStock: true,
    prescriptionRequired: false,
    image: "/medicines/blister.png",
    description: "NSAID for pain, inflammation and fever",
    uses: ["Pain relief", "Inflammation", "Fever", "Menstrual cramps"],
    dosage: "1 tablet every 6-8 hours with food",
    sideEffects: ["Stomach upset", "Nausea", "Dizziness"],
    warnings: ["Take with food", "Avoid if stomach ulcers", "Not for long-term use without doctor supervision"],
    manufacturer: "Abbott India",
    expiryDate: "2026-10",
    composition: "Ibuprofen 400mg",
  },
  {
    id: "med-008",
    name: "Multivitamin Daily",
    brand: "Supradyn",
    category: "Vitamins",
    price: 320,
    originalPrice: 399,
    rating: 4.8,
    reviews: 8234,
    inStock: true,
    prescriptionRequired: false,
    image: "/medicines/supradyn.png",
    description: "Complete daily multivitamin and mineral supplement",
    uses: ["Daily nutrition", "Energy boost", "Immunity", "Overall health"],
    dosage: "1 tablet daily after breakfast",
    sideEffects: ["Nausea (if taken on empty stomach)", "Dark urine (harmless)"],
    warnings: ["Keep out of reach of children", "Not a substitute for balanced diet"],
    manufacturer: "Bayer",
    expiryDate: "2027-01",
    composition: "13 vitamins + 10 minerals",
  },
];

// =============================================
// MOCK DATA - Doctors
// =============================================
export const doctors = [
  {
    id: "doc-001",
    name: "Dr. Priya Sharma",
    specialty: "Cardiologist",
    qualification: "MBBS, MD (Cardiology), DM",
    experience: 14,
    rating: 4.9,
    reviews: 1243,
    consultationFee: 800,
    hospital: "Apollo Hospitals, Delhi",
    avatar: "👩‍⚕️",
    available: true,
    nextSlot: "Today, 3:00 PM",
    languages: ["English", "Hindi"],
    about: "Senior Cardiologist with 14 years of experience in interventional cardiology and heart failure management.",
    timings: ["Mon-Fri: 9 AM - 5 PM", "Sat: 9 AM - 1 PM"],
    patients: 4521,
    awards: ["Best Cardiologist Award 2023", "Medical Excellence Award 2021"],
    conditions: ["Heart disease", "Hypertension", "Arrhythmia", "Heart failure"],
  },
  {
    id: "doc-002",
    name: "Dr. Rajesh Kumar",
    specialty: "Neurologist",
    qualification: "MBBS, MD, DM (Neurology)",
    experience: 18,
    rating: 4.8,
    reviews: 987,
    consultationFee: 1000,
    hospital: "Fortis Hospital, Mumbai",
    avatar: "👨‍⚕️",
    available: true,
    nextSlot: "Tomorrow, 10:00 AM",
    languages: ["English", "Hindi", "Marathi"],
    about: "Expert neurologist specializing in stroke management, epilepsy, and movement disorders.",
    timings: ["Mon-Sat: 10 AM - 6 PM"],
    patients: 6234,
    awards: ["Neurology Excellence 2022"],
    conditions: ["Migraine", "Epilepsy", "Stroke", "Parkinson's"],
  },
  {
    id: "doc-003",
    name: "Dr. Sneha Patel",
    specialty: "Dermatologist",
    qualification: "MBBS, MD (Dermatology)",
    experience: 9,
    rating: 4.9,
    reviews: 2341,
    consultationFee: 600,
    hospital: "Max Hospital, Bangalore",
    avatar: "👩‍⚕️",
    available: true,
    nextSlot: "Today, 5:30 PM",
    languages: ["English", "Hindi", "Gujarati"],
    about: "Skilled dermatologist with expertise in cosmetic dermatology, acne treatment, and skin cancer screening.",
    timings: ["Mon-Fri: 11 AM - 7 PM", "Sat: 10 AM - 3 PM"],
    patients: 8901,
    awards: ["Best Dermatologist Mumbai 2023"],
    conditions: ["Acne", "Eczema", "Psoriasis", "Hair loss", "Skin cancer"],
  },
  {
    id: "doc-004",
    name: "Dr. Arjun Mehta",
    specialty: "Psychiatrist",
    qualification: "MBBS, MD (Psychiatry), DNB",
    experience: 11,
    rating: 4.7,
    reviews: 567,
    consultationFee: 900,
    hospital: "NIMHANS, Bangalore",
    avatar: "👨‍⚕️",
    available: false,
    nextSlot: "Dec 20, 9:00 AM",
    languages: ["English", "Hindi", "Kannada"],
    about: "Compassionate psychiatrist specializing in depression, anxiety, and addiction treatment with CBT expertise.",
    timings: ["Tue-Sat: 9 AM - 5 PM"],
    patients: 3456,
    awards: ["Mental Health Advocacy Award 2022"],
    conditions: ["Depression", "Anxiety", "ADHD", "OCD", "Bipolar disorder"],
  },
  {
    id: "doc-005",
    name: "Dr. Meera Iyer",
    specialty: "Dentist",
    qualification: "BDS, MDS (Orthodontics)",
    experience: 7,
    rating: 4.8,
    reviews: 1876,
    consultationFee: 500,
    hospital: "SmileMore Dental Clinic, Chennai",
    avatar: "👩‍⚕️",
    available: true,
    nextSlot: "Today, 2:00 PM",
    languages: ["English", "Hindi", "Tamil"],
    about: "Expert dental surgeon specializing in orthodontics, implants, and cosmetic dentistry.",
    timings: ["Mon-Sat: 9 AM - 8 PM"],
    patients: 5678,
    awards: ["Best Dental Practice Award 2023"],
    conditions: ["Tooth decay", "Gum disease", "Orthodontics", "Implants"],
  },
  {
    id: "doc-006",
    name: "Dr. Vikram Singh",
    specialty: "General Physician",
    qualification: "MBBS, MD (General Medicine)",
    experience: 12,
    rating: 4.6,
    reviews: 3421,
    consultationFee: 400,
    hospital: "City Health Clinic, Hyderabad",
    avatar: "👨‍⚕️",
    available: true,
    nextSlot: "Today, 4:30 PM",
    languages: ["English", "Hindi", "Telugu"],
    about: "Experienced general physician for all routine health concerns, chronic disease management, and preventive care.",
    timings: ["Mon-Sat: 8 AM - 9 PM"],
    patients: 12456,
    awards: [],
    conditions: ["Fever", "Cold", "Diabetes", "Hypertension", "General checkup"],
  },
];

// =============================================
// MOCK DATA - Health Metrics
// =============================================
export const healthMetrics = {
  heartRate: {
    current: 72,
    unit: "bpm",
    trend: "+2",
    status: "normal",
    history: [68, 71, 73, 70, 72, 75, 72, 69, 72, 74, 71, 72],
  },
  bloodPressure: {
    systolic: 120,
    diastolic: 80,
    unit: "mmHg",
    trend: "stable",
    status: "normal",
    history: [
      { systolic: 118, diastolic: 78 },
      { systolic: 122, diastolic: 81 },
      { systolic: 120, diastolic: 80 },
      { systolic: 119, diastolic: 79 },
      { systolic: 121, diastolic: 80 },
      { systolic: 120, diastolic: 80 },
    ],
  },
  steps: {
    current: 8432,
    goal: 10000,
    unit: "steps",
    trend: "+1200",
    status: "good",
    history: [6200, 7800, 9100, 5400, 8432, 7200, 9800, 8100, 8432, 10200, 7600, 8432],
  },
  sleep: {
    current: 7.5,
    unit: "hours",
    trend: "+0.5",
    status: "good",
    quality: "Deep",
    history: [6, 7, 8, 6.5, 7.5, 7, 8, 7.5, 6.5, 7.5, 8, 7.5],
  },
  water: {
    current: 1.8,
    goal: 2.5,
    unit: "liters",
    trend: "+0.3",
    status: "moderate",
    history: [1.5, 2.0, 2.2, 1.8, 2.5, 1.9, 2.1, 1.8, 2.3, 1.8, 2.0, 1.8],
  },
  calories: {
    current: 1845,
    goal: 2200,
    unit: "kcal",
    trend: "-120",
    status: "good",
    burned: 420,
    history: [1980, 1750, 2100, 1850, 1845, 2000, 1760, 1900, 1845, 2100, 1800, 1845],
  },
  bloodSugar: {
    current: 95,
    unit: "mg/dL",
    trend: "-5",
    status: "normal",
    history: [98, 102, 95, 100, 95, 97, 93, 95, 98, 95, 97, 95],
  },
  bmi: {
    value: 22.4,
    weight: 68,
    height: 174,
    category: "Normal",
    trend: "-0.2",
  },
};

// =============================================
// MOCK DATA - Weekly Health Charts
// =============================================
export const weeklyData = [
  { day: "Mon", steps: 6200, calories: 1980, sleep: 6, water: 1.5, heartRate: 68 },
  { day: "Tue", steps: 7800, calories: 1750, sleep: 7, water: 2.0, heartRate: 71 },
  { day: "Wed", steps: 9100, calories: 2100, sleep: 8, water: 2.2, heartRate: 73 },
  { day: "Thu", steps: 5400, calories: 1850, sleep: 6.5, water: 1.8, heartRate: 70 },
  { day: "Fri", steps: 8432, calories: 1845, sleep: 7.5, water: 1.8, heartRate: 72 },
  { day: "Sat", steps: 10200, calories: 2300, sleep: 8.5, water: 2.5, heartRate: 75 },
  { day: "Sun", steps: 4500, calories: 1600, sleep: 9, water: 2.0, heartRate: 65 },
];

// =============================================
// MOCK DATA - AI Quick Replies
// =============================================
export const quickReplies = {
  doctor: [
    "What are my symptoms suggesting?",
    "When should I see a specialist?",
    "What medications can I take?",
    "Is this condition serious?",
  ],
  therapist: [
    "I'm feeling anxious today",
    "Help me manage stress",
    "I can't sleep properly",
    "Talk me through breathing exercises",
  ],
  fitnessCoach: [
    "Suggest a workout for today",
    "How many calories did I burn?",
    "Best exercises for weight loss?",
    "I want to build muscle",
  ],
  nutritionExpert: [
    "What should I eat today?",
    "Suggest a diet plan",
    "Best foods for immunity?",
    "How to lose weight with diet?",
  ],
  general: [
    "Tell me a health tip",
    "What's good for energy?",
    "How to stay healthy?",
    "Recommend vitamins for me",
  ],
};

// =============================================
// MOCK DATA - Admin Stats
// =============================================
export const adminStats = {
  totalUsers: 48291,
  totalDoctors: 234,
  totalMedicines: 1847,
  totalOrders: 12430,
  totalRevenue: 2847500,
  activeConsultations: 42,
  pendingOrders: 187,
  newUsersToday: 234,
};

// =============================================
// MOCK DATA - AI Chat Responses
// =============================================
export const aiResponses: Record<string, string[]> = {
  fever: [
    "Based on your symptoms, you appear to have a fever 🌡️. Here's what I recommend:\n\n**Immediate Steps:**\n- Rest and stay hydrated (drink 8-10 glasses of water)\n- Take Paracetamol 500mg if temperature exceeds 101°F\n- Apply cool compress on forehead\n\n**Diet Advice:**\n- Light foods: khichdi, soups, fresh fruits\n- Avoid oily and spicy foods\n- Coconut water and ORS for electrolytes\n\n**Warning Signs - See a Doctor if:**\n- Fever exceeds 103°F (39.4°C)\n- Symptoms persist beyond 3 days\n- Difficulty breathing\n- Severe headache or stiff neck\n\n⚠️ *Disclaimer: This is general information only. Please consult a qualified doctor for medical advice.*",
  ],
  headache: [
    "Headaches can have many causes 🤕. Let me help you:\n\n**Common Causes:**\n- Dehydration\n- Stress and tension\n- Eye strain\n- Poor sleep\n- Sinus issues\n\n**Relief Measures:**\n- Drink 2-3 glasses of water\n- Rest in a quiet, dark room\n- Gentle neck and shoulder massage\n- Apply peppermint oil on temples\n\n**Medications (OTC):**\n- Paracetamol 500mg\n- Ibuprofen 400mg (with food)\n\n**Consult Doctor if:**\n- Sudden severe headache ('thunderclap')\n- Headache with vision changes\n- Persistent headaches for >2 weeks\n\n⚠️ *This is general health information. Consult a doctor for persistent symptoms.*",
  ],
  default: [
    "I'm MediMind AI, your intelligent health assistant! 🏥\n\nI can help you with:\n- 🔍 **Symptom Analysis** - Tell me what you're feeling\n- 💊 **Medicine Information** - Dosage, side effects, interactions\n- 🥗 **Diet & Nutrition** - Personalized food recommendations\n- 🏃 **Fitness Advice** - Exercise and wellness tips\n- 🚨 **Emergency Guidance** - When to seek immediate help\n\n**Quick questions you can ask:**\n- \"I have a fever and sore throat\"\n- \"What's good for diabetes diet?\"\n- \"I feel anxious and stressed\"\n- \"Suggest exercises for back pain\"\n\nWhat health concern can I help you with today? 😊",
  ],
  hindi: [
    "नमस्ते! मैं MediMind AI हूँ, आपका स्वास्थ्य सहायक! 🏥\n\nमैं आपकी इन चीजों में मदद कर सकता हूँ:\n- 🔍 **लक्षण विश्लेषण** - बताइए आप कैसा महसूस कर रहे हैं\n- 💊 **दवाइयों की जानकारी** - खुराक, दुष्प्रभाव\n- 🥗 **आहार सलाह** - क्या खाएं, क्या न खाएं\n- 🏃 **व्यायाम सुझाव** - स्वस्थ रहने के टिप्स\n- 🚨 **आपातकालीन मार्गदर्शन** - कब डॉक्टर से मिलें\n\nआज आपकी क्या स्वास्थ्य समस्या है? बेझिझक पूछें! 😊\n\n⚠️ *यह सामान्य स्वास्थ्य जानकारी है। गंभीर समस्याओं के लिए डॉक्टर से मिलें।*",
  ],
  emergency: [
    "🚨 **EMERGENCY ALERT - SEEK IMMEDIATE MEDICAL HELP!**\n\nThe symptoms you've described may be life-threatening. Please:\n\n1. **Call 112 (Emergency)** or **102 (Ambulance)** immediately\n2. **Do NOT drive yourself** to the hospital\n3. If unconscious: Check breathing, start CPR if trained\n4. For chest pain: Sit upright, loosen tight clothing\n5. **Nearest Hospital Finder**: [Open Emergency Mode]\n\n**DO NOT delay** - Every second matters in medical emergencies!\n\nStay on the line with emergency services until help arrives.",
  ],
};

// =============================================
// MOCK DATA - Order Tracking Steps
// =============================================
export const orderSteps = [
  { id: 1, label: "Order Placed", icon: "📋", completed: true, time: "10:30 AM" },
  { id: 2, label: "Confirmed", icon: "✅", completed: true, time: "10:35 AM" },
  { id: 3, label: "Packed", icon: "📦", completed: true, time: "11:00 AM" },
  { id: 4, label: "Shipped", icon: "🚚", completed: false, time: "Expected 1 PM" },
  { id: 5, label: "Delivered", icon: "🏠", completed: false, time: "Expected 4 PM" },
];

// =============================================
// MOCK DATA - Notifications
// =============================================
export const notifications = [
  { id: 1, type: "medicine", message: "Time to take Metformin 500mg 💊", time: "2 min ago", unread: true },
  { id: 2, type: "appointment", message: "Dr. Priya Sharma consultation in 1 hour 👨‍⚕️", time: "1 hour ago", unread: true },
  { id: 3, type: "health", message: "You've completed 80% of your daily steps goal 🏃", time: "3 hours ago", unread: false },
  { id: 4, type: "order", message: "Your medicine order is out for delivery 🚚", time: "5 hours ago", unread: false },
  { id: 5, type: "tip", message: "AI Health Tip: Drink water before each meal 💧", time: "1 day ago", unread: false },
];

// =============================================
// MOCK USER
// =============================================
export const mockUser = {
  id: "user-001",
  name: "Rambali Sharma",
  email: "rambali@example.com",
  phone: "+91 9876543210",
  age: 32,
  gender: "Male",
  bloodGroup: "B+",
  height: 174,
  weight: 68,
  avatar: "👨",
  memberSince: "January 2024",
  conditions: ["Mild Hypertension"],
  allergies: ["Penicillin"],
  address: "A-204, Sunshine Apartments, Sector 15, Noida, UP 201301",
};
