import { create } from "zustand";
import { persist } from "zustand/middleware";

export interface Medicine {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  originalPrice: number;
  rating: number;
  reviews: number;
  inStock: boolean;
  prescriptionRequired: boolean;
  image: string;
  description: string;
  uses: string[];
  dosage: string;
  sideEffects: string[];
  warnings: string[];
  manufacturer: string;
  expiryDate: string;
  composition: string;
}

interface MedicineStore {
  medicines: Medicine[];
  addMedicine: (medicine: Omit<Medicine, "id" | "rating" | "reviews">) => void;
  toggleStock: (id: string) => void;
  removeMedicine: (id: string) => void;
  clearAll: () => void;
}

export const useMedicineStore = create<MedicineStore>()(
  persist(
    (set) => ({
      medicines: [
        {
          id: "med-001",
          name: "Amlodipine & Atenolol",
          brand: "Amlowal AT",
          category: "Cardiovascular",
          price: 45,
          originalPrice: 60,
          rating: 4.8,
          reviews: 128,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Calcium channel blocker and beta-blocker combination used to treat high blood pressure (hypertension).",
          uses: ["High Blood Pressure"],
          dosage: "1 tablet daily or as advised by physician",
          sideEffects: ["Dizziness", "Fatigue", "Ankle swelling"],
          warnings: ["Monitor blood pressure regularly", "Do not stop taking abruptly"],
          manufacturer: "Alkem Laboratories Ltd",
          expiryDate: "2027-12",
          composition: "Amlodipine 5mg + Atenolol 50mg",
        },
        {
          id: "med-002",
          name: "Propranolol Hydrochloride",
          brand: "Ciplar-10",
          category: "Cardiovascular",
          price: 25,
          originalPrice: 32,
          rating: 4.6,
          reviews: 234,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Beta-blocker that helps treat irregular heartbeats and prevent migraine attacks.",
          uses: ["Heart Rhythm Disorders", "Migraine Prevention"],
          dosage: "1 tablet daily or as advised by physician",
          sideEffects: ["Tiredness", "Cold hands or feet", "Difficulty sleeping"],
          warnings: ["Do not use if you have asthma", "Consult doctor before discontinuing"],
          manufacturer: "Cipla Ltd",
          expiryDate: "2027-10",
          composition: "Propranolol Hydrochloride 10mg",
        },
        {
          id: "med-003",
          name: "Nifedipine",
          brand: "Depin-5",
          category: "Cardiovascular",
          price: 15,
          originalPrice: 20,
          rating: 4.7,
          reviews: 88,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Calcium channel blocker used to manage high blood pressure and prevent chest pain (angina).",
          uses: ["High Blood Pressure", "Chest Pain (Angina)"],
          dosage: "1 tablet daily or as advised by physician",
          sideEffects: ["Headache", "Swelling of ankles", "Nausea"],
          warnings: ["Avoid eating grapefruit or drinking grapefruit juice"],
          manufacturer: "Zydus Cadila",
          expiryDate: "2027-09",
          composition: "Nifedipine 5mg",
        },
        {
          id: "med-004",
          name: "Diltiazem Hydrochloride",
          brand: "Dilzem-30",
          category: "Cardiovascular",
          price: 35,
          originalPrice: 45,
          rating: 4.5,
          reviews: 112,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Used to prevent chest pain (angina) and manage high blood pressure.",
          uses: ["Heart Disease", "High Blood Pressure"],
          dosage: "1 tablet daily or as advised by physician",
          sideEffects: ["Dizziness", "Headache", "Constipation"],
          warnings: ["Monitor heart rate regularly", "Do not take with beta-blockers without doctor supervision"],
          manufacturer: "Torrent Pharmaceuticals",
          expiryDate: "2027-08",
          composition: "Diltiazem Hydrochloride 30mg",
        },
        {
          id: "med-005",
          name: "Spironolactone",
          brand: "Aldactone-100",
          category: "Cardiovascular",
          price: 85,
          originalPrice: 110,
          rating: 4.7,
          reviews: 156,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Potassium-sparing diuretic used to reduce swelling and manage high blood pressure.",
          uses: ["Fluid Retention (Edema)", "High Blood Pressure"],
          dosage: "1 tablet daily in the morning",
          sideEffects: ["Nausea", "Dizziness", "Increased potassium levels"],
          warnings: ["Avoid potassium supplements", "Regular blood tests required"],
          manufacturer: "RPG Life Sciences",
          expiryDate: "2027-11",
          composition: "Spironolactone 100mg",
        },
        {
          id: "med-006",
          name: "Furosemide",
          brand: "Lasix",
          category: "Cardiovascular",
          price: 12,
          originalPrice: 15,
          rating: 4.8,
          reviews: 450,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Loop diuretic to reduce fluid retention and edema caused by congestive heart failure.",
          uses: ["Swelling (Edema)", "High Blood Pressure"],
          dosage: "1 tablet daily in the morning",
          sideEffects: ["Dehydration", "Electrolyte imbalance", "Dizziness"],
          warnings: ["May lower potassium levels", "Take in the morning to avoid night urination"],
          manufacturer: "Sanofi India",
          expiryDate: "2027-06",
          composition: "Furosemide 40mg",
        },
        {
          id: "med-007",
          name: "Isosorbide Dinitrate",
          brand: "Sorbitrate-5",
          category: "Cardiovascular",
          price: 20,
          originalPrice: 25,
          rating: 4.9,
          reviews: 610,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Vasodilator used to prevent chest pain (angina).",
          uses: ["Heart Chest Pain (Angina)"],
          dosage: "1 tablet sublingually or as directed",
          sideEffects: ["Headache", "Flushing", "Dizziness"],
          warnings: ["Do not use with erectile dysfunction drugs like sildenafil"],
          manufacturer: "Abbott India",
          expiryDate: "2027-05",
          composition: "Isosorbide Dinitrate 5mg",
        },
        {
          id: "med-008",
          name: "Ramipril",
          brand: "Ramirace-5",
          category: "Cardiovascular",
          price: 45,
          originalPrice: 55,
          rating: 4.7,
          reviews: 290,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "ACE inhibitor used to treat high blood pressure and prevent heart failure.",
          uses: ["High Blood Pressure", "Heart Failure Prevention"],
          dosage: "1 tablet daily or as advised by physician",
          sideEffects: ["Dry cough", "Dizziness", "Headache"],
          warnings: ["Not for use in pregnancy", "Monitor kidney function"],
          manufacturer: "Sun Pharmaceutical Industries",
          expiryDate: "2027-04",
          composition: "Ramipril 5mg",
        },
        {
          id: "med-009",
          name: "Glimepiride, Voglibose & Metformin",
          brand: "Glimeace-MV2",
          category: "Diabetes",
          price: 145,
          originalPrice: 185,
          rating: 4.8,
          reviews: 320,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/green_box.png",
          description: "Combination anti-diabetic medication to control high blood sugar in type 2 diabetes.",
          uses: ["Type 2 Diabetes Control"],
          dosage: "1 tablet daily with or immediately after meals",
          sideEffects: ["Hypoglycemia", "Nausea", "Flatulence"],
          warnings: ["Monitor blood sugar levels regularly", "Avoid alcohol"],
          manufacturer: "Torrent Pharmaceuticals",
          expiryDate: "2027-03",
          composition: "Glimepiride 2mg + Voglibose 0.2mg + Metformin 500mg",
        },
        {
          id: "med-010",
          name: "Teneligliptin",
          brand: "Tenewal-20",
          category: "Diabetes",
          price: 95,
          originalPrice: 120,
          rating: 4.6,
          reviews: 140,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/green_box.png",
          description: "DPP-4 inhibitor used to treat type 2 diabetes mellitus.",
          uses: ["Type 2 Diabetes Treatment"],
          dosage: "1 tablet once daily before or after meals",
          sideEffects: ["Hypoglycemia", "Headache", "Upper respiratory tract infection"],
          warnings: ["Consult doctor if you have kidney or liver issues"],
          manufacturer: "Alkem Laboratories Ltd",
          expiryDate: "2027-02",
          composition: "Teneligliptin 20mg",
        },
        {
          id: "med-011",
          name: "Aceclofenac & Paracetamol",
          brand: "Aceclowal P",
          category: "Pain Relief",
          price: 65,
          originalPrice: 80,
          rating: 4.7,
          reviews: 890,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/tablets_blister.png",
          description: "Effective pain reliever and anti-inflammatory drug for joints and body aches.",
          uses: ["Pain Relief", "Fever Reduction", "Joint Pain"],
          dosage: "1 tablet twice daily after meals",
          sideEffects: ["Heartburn", "Stomach pain", "Nausea"],
          warnings: ["Do not take on empty stomach", "Avoid alcohol"],
          manufacturer: "Aristo Pharmaceuticals",
          expiryDate: "2027-12",
          composition: "Aceclofenac 100mg + Paracetamol 325mg",
        },
        {
          id: "med-012",
          name: "Aceclofenac, Paracetamol & Chlorzoxazone",
          brand: "Aceclowal MR",
          category: "Pain Relief",
          price: 90,
          originalPrice: 115,
          rating: 4.6,
          reviews: 750,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Combination muscle relaxant and pain reliever for muscle spasms and back pain.",
          uses: ["Muscle Strain", "Spasms and Pain"],
          dosage: "1 tablet twice daily after meals",
          sideEffects: ["Drowsiness", "Dizziness", "Stomach upset"],
          warnings: ["May cause drowsiness", "Avoid driving or heavy machinery usage"],
          manufacturer: "Aristo Pharmaceuticals",
          expiryDate: "2027-11",
          composition: "Aceclofenac 100mg + Paracetamol 325mg + Chlorzoxazone 250mg",
        },
        {
          id: "med-013",
          name: "Aceclofenac & Thiocolchicoside",
          brand: "Thiodoc Acc-4",
          category: "Pain Relief",
          price: 180,
          originalPrice: 220,
          rating: 4.8,
          reviews: 290,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Used to treat muscle pain, spasms, and stiffness.",
          uses: ["Muscle Stiffness", "Back Pain", "Spasms"],
          dosage: "1 tablet twice daily after meals",
          sideEffects: ["Nausea", "Dizziness", "Drowsiness"],
          warnings: ["Not recommended for pregnant or breastfeeding women"],
          manufacturer: "Macleods Pharmaceuticals",
          expiryDate: "2027-10",
          composition: "Aceclofenac 100mg + Thiocolchicoside 4mg",
        },
        {
          id: "med-014",
          name: "Trypsin-Chymotrypsin",
          brand: "Chymewal-forte",
          category: "Pain Relief",
          price: 240,
          originalPrice: 300,
          rating: 4.7,
          reviews: 180,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Enzyme formulation to reduce swelling, inflammation, and promote tissue healing.",
          uses: ["Reducing Swelling", "Post-surgery Healing"],
          dosage: "1-2 tablets three times a day on empty stomach",
          sideEffects: ["Nausea", "Digestive disturbances", "Skin rash (rare)"],
          warnings: ["Take on empty stomach 30 mins before food"],
          manufacturer: "Wallace Pharmaceuticals",
          expiryDate: "2027-09",
          composition: "Trypsin-Chymotrypsin 100,000 Armour Units",
        },
        {
          id: "med-015",
          name: "Etoricoxib",
          brand: "Etoxowal-120",
          category: "Pain Relief",
          price: 130,
          originalPrice: 165,
          rating: 4.7,
          reviews: 420,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Selective COX-2 inhibitor used to relieve pain and inflammation in osteoarthritis and gout.",
          uses: ["Joint Pain", "Arthritis Pain", "Bone Pain"],
          dosage: "1 tablet daily after meals",
          sideEffects: ["Headache", "Swelling of feet", "Heartburn"],
          warnings: ["Avoid if you have active stomach ulcers or heart problems"],
          manufacturer: "Lupin Ltd",
          expiryDate: "2027-08",
          composition: "Etoricoxib 120mg",
        },
        {
          id: "med-016",
          name: "Leflunomide",
          brand: "Lefsum-20",
          category: "Pain Relief",
          price: 190,
          originalPrice: 240,
          rating: 4.5,
          reviews: 98,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Disease-modifying antirheumatic drug (DMARD) used to treat moderate-to-severe active rheumatoid arthritis.",
          uses: ["Rheumatoid Arthritis", "Joint Swelling"],
          dosage: "1 tablet once daily",
          sideEffects: ["Diarrhea", "Nausea", "Hair loss (temporary)"],
          warnings: ["Monitor liver enzymes regularly", "Highly contraindicated in pregnancy"],
          manufacturer: "Ipca Laboratories",
          expiryDate: "2027-07",
          composition: "Leflunomide 20mg",
        },
        {
          id: "med-017",
          name: "Ketorolac Tromethamine",
          brand: "Ketoride-DT",
          category: "Pain Relief",
          price: 48,
          originalPrice: 60,
          rating: 4.8,
          reviews: 510,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Dispersible non-steroidal anti-inflammatory drug (NSAID) for short-term management of acute severe pain, like toothache.",
          uses: ["Severe Toothache", "Post-surgical Pain"],
          dosage: "1 tablet dissolved in half glass of water as needed",
          sideEffects: ["Stomach pain", "Heartburn", "Nausea"],
          warnings: ["Do not use for more than 5 days", "Avoid if you have kidney problems"],
          manufacturer: "Zuventus Healthcare",
          composition: "Ketorolac Tromethamine 10mg",
          expiryDate: "2027-06",
        },
        {
          id: "med-018",
          name: "Mefenamic Acid & Dicyclomine",
          brand: "Melwal-Plus",
          category: "Pain Relief",
          price: 38,
          originalPrice: 50,
          rating: 4.6,
          reviews: 390,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Relieves muscle spasms, abdominal pain, and menstrual cramps effectively.",
          uses: ["Stomach Pain", "Abdominal Cramps", "Menstrual Cramps"],
          dosage: "1 tablet three times daily after meals",
          sideEffects: ["Drowsiness", "Dry mouth", "Blurred vision"],
          warnings: ["Avoid driving while taking this medication due to potential blurred vision"],
          manufacturer: "Wallace Pharmaceuticals",
          expiryDate: "2027-05",
          composition: "Mefenamic Acid 250mg + Dicyclomine Hydrochloride 10mg",
        },
        {
          id: "med-019",
          name: "Paracetamol",
          brand: "Parawat-500",
          category: "Pain Relief",
          price: 15,
          originalPrice: 20,
          rating: 4.7,
          reviews: 1200,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/tablets_blister.png",
          description: "Standard antipyretic and analgesic for fever and body ache relief.",
          uses: ["Fever Treatment", "Body Pain Relief"],
          dosage: "1-2 tablets every 4-6 hours. Max 8 tablets daily.",
          sideEffects: ["None under normal doses", "Liver toxicity with overdose"],
          warnings: ["Do not take with other Paracetamol containing drugs"],
          manufacturer: "Alkem Laboratories Ltd",
          expiryDate: "2027-04",
          composition: "Paracetamol 500mg",
        },
        {
          id: "med-020",
          name: "Piroxicam",
          brand: "Pirox-DT-20",
          category: "Pain Relief",
          price: 35,
          originalPrice: 45,
          rating: 4.6,
          reviews: 210,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Dispersible anti-inflammatory tablets for joint and arthritis pain.",
          uses: ["Joint Pain", "Arthritis Relief", "Stiffness"],
          dosage: "1 tablet dissolved in water daily after meals",
          sideEffects: ["Indigestion", "Stomach ache", "Nausea"],
          warnings: ["Take with food", "Not for patients with history of gastrointestinal bleeding"],
          manufacturer: "Sun Pharma",
          expiryDate: "2027-03",
          composition: "Piroxicam 20mg",
        },
        {
          id: "med-021",
          name: "Nimesulide",
          brand: "Panidea",
          category: "Pain Relief",
          price: 30,
          originalPrice: 40,
          rating: 4.5,
          reviews: 180,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Non-steroidal anti-inflammatory drug (NSAID) for rapid relief of acute pain, joints, and swelling.",
          uses: ["Severe Pain", "Swelling Reduction"],
          dosage: "1 tablet twice daily after meals",
          sideEffects: ["Nausea", "Vomiting", "Liver enzyme elevation"],
          warnings: ["Use for short duration only due to potential liver safety issues"],
          manufacturer: "Apex Laboratories",
          expiryDate: "2027-02",
          composition: "Nimesulide 100mg",
        },
        {
          id: "med-022",
          name: "Allopurinol",
          brand: "Zyrik-100",
          category: "Pain Relief",
          price: 22,
          originalPrice: 30,
          rating: 4.8,
          reviews: 310,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Helps lower uric acid levels in the blood, preventing gout attacks and kidney stones.",
          uses: ["Reducing Uric Acid", "Gout Treatment"],
          dosage: "1 tablet daily after food",
          sideEffects: ["Drowsiness", "Stomach upset", "Skin rash"],
          warnings: ["Drink plenty of fluids while taking this", "Discontinue if rash develops"],
          manufacturer: "Cipla Ltd",
          expiryDate: "2027-01",
          composition: "Allopurinol 100mg",
        },
        {
          id: "med-023",
          name: "Tramadol & Acetaminophen",
          brand: "Tramawal Plus",
          category: "Pain Relief",
          price: 110,
          originalPrice: 140,
          rating: 4.7,
          reviews: 440,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Strong pain reliever combining tramadol and acetaminophen for severe acute pain.",
          uses: ["Severe Pain Relief", "Chronic Pain"],
          dosage: "1 tablet every 6 hours as prescribed",
          sideEffects: ["Nausea", "Drowsiness", "Constipation", "Dry mouth"],
          warnings: ["Habit-forming medication", "Do not consume alcohol", "Avoid driving"],
          manufacturer: "Lupin Ltd",
          expiryDate: "2026-12",
          composition: "Tramadol Hydrochloride 37.5mg + Paracetamol 325mg",
        },
        {
          id: "med-024",
          name: "Colchicine",
          brand: "Zycotchin",
          category: "Pain Relief",
          price: 75,
          originalPrice: 95,
          rating: 4.6,
          reviews: 120,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Specific medication used to treat and prevent acute gout attacks.",
          uses: ["Gout Flare-ups", "Joint Pain"],
          dosage: "1 tablet daily or as advised during gout attack",
          sideEffects: ["Diarrhea", "Abdominal cramps", "Nausea"],
          warnings: ["Reduce dose if diarrhea occurs", "Regular blood monitoring required"],
          manufacturer: "Zydus Cadila",
          expiryDate: "2026-11",
          composition: "Colchicine 0.5mg",
        },
        {
          id: "med-025",
          name: "Naproxen",
          brand: "Naproxen-500",
          category: "Pain Relief",
          price: 55,
          originalPrice: 70,
          rating: 4.7,
          reviews: 290,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Long-acting NSAID for relief of joint swelling, stiffness, and arthritis pain.",
          uses: ["Swelling & Pain", "Arthritis Pain"],
          dosage: "1 tablet twice daily with food",
          sideEffects: ["Heartburn", "Stomach upset", "Headache"],
          warnings: ["Take with meals", "Do not take with other NSAIDs"],
          manufacturer: "Micro Labs Ltd",
          expiryDate: "2026-10",
          composition: "Naproxen 500mg",
        },
        {
          id: "med-026",
          name: "Nimesulide & Paracetamol",
          brand: "Nimugin-P",
          category: "Pain Relief",
          price: 45,
          originalPrice: 58,
          rating: 4.6,
          reviews: 480,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Combination tablet for quick relief from acute body pain, headache, and fever.",
          uses: ["Acute Pain Relief", "Fever and Body Ache"],
          dosage: "1 tablet twice daily after food",
          sideEffects: ["Indigestion", "Nausea", "Dizziness"],
          warnings: ["Avoid prolonged usage without consulting doctor"],
          manufacturer: "GSK India",
          expiryDate: "2026-09",
          composition: "Nimesulide 100mg + Paracetamol 325mg",
        },
        {
          id: "med-027",
          name: "Cefixime & Lactic Acid Bacillus",
          brand: "Cefibact-LB",
          category: "Antibiotic",
          price: 185,
          originalPrice: 230,
          rating: 4.8,
          reviews: 670,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Antibiotic with lactobacillus to protect stomach gut flora from diarrhea side effects during therapy.",
          uses: ["Throat Infections", "Lung Infections", "Typhoid Fever"],
          dosage: "1 tablet twice daily for 5-7 days as prescribed",
          sideEffects: ["Mild stomach discomfort", "Diarrhea (rare due to probiotics)"],
          warnings: ["Complete full course of antibiotics", "Do not skip doses"],
          manufacturer: "Aristo Pharmaceuticals",
          expiryDate: "2026-08",
          composition: "Cefixime 200mg + Lactic Acid Bacillus 60M Spores",
        },
        {
          id: "med-028",
          name: "Ciprofloxacin",
          brand: "Cipman-500",
          category: "Antibiotic",
          price: 45,
          originalPrice: 58,
          rating: 4.5,
          reviews: 830,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Broad-spectrum fluoroquinolone antibiotic used for bacterial infections of stomach and urinary tract.",
          uses: ["Stomach Infections", "Typhoid Fever", "Urine Infections"],
          dosage: "1 tablet twice daily for 3-5 days as prescribed",
          sideEffects: ["Nausea", "Diarrhea", "Photosensitivity"],
          warnings: ["Avoid exposure to direct sunlight", "Avoid taking with dairy products"],
          manufacturer: "Cipla Ltd",
          expiryDate: "2026-07",
          composition: "Ciprofloxacin 500mg",
        },
        {
          id: "med-029",
          name: "Clindamycin",
          brand: "Clindacad-300",
          category: "Antibiotic",
          price: 210,
          originalPrice: 265,
          rating: 4.7,
          reviews: 140,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Antibiotic used to treat severe infections of skin, soft tissues, and bones.",
          uses: ["Skin Infections", "Bone Infections"],
          dosage: "1 tablet three times daily as prescribed",
          sideEffects: ["Diarrhea", "Nausea", "Stomach pain"],
          warnings: ["Report severe watery diarrhea immediately", "Take with full glass of water"],
          manufacturer: "Cadila Pharmaceuticals",
          expiryDate: "2026-06",
          composition: "Clindamycin 300mg",
        },
        {
          id: "med-030",
          name: "Levofloxacin",
          brand: "Levoace-500",
          category: "Antibiotic",
          price: 52,
          originalPrice: 68,
          rating: 4.6,
          reviews: 390,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Quinolone antibiotic for skin, sinus, lung, and urinary tract bacterial infections.",
          uses: ["Bacterial Infections", "Pneumonia", "Sinusitis"],
          dosage: "1 tablet daily as prescribed",
          sideEffects: ["Headache", "Nausea", "Dizziness"],
          warnings: ["Drink plenty of water", "Stop immediately if tendon pain occurs"],
          manufacturer: "Alkem Laboratories Ltd",
          expiryDate: "2027-12",
          composition: "Levofloxacin 500mg",
        },
        {
          id: "med-031",
          name: "Linezolid",
          brand: "Linowal-600",
          category: "Antibiotic",
          price: 360,
          originalPrice: 450,
          rating: 4.8,
          reviews: 110,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Strong synthetic antibiotic for serious bacterial infections resistant to other medicines.",
          uses: ["Severe Skin Infections", "Pneumonia (Resistant cases)"],
          dosage: "1 tablet twice daily as prescribed",
          sideEffects: ["Headache", "Nausea", "Diarrhea", "Anemia (long term)"],
          warnings: ["Avoid tyramine-rich food like cheese and red wine", "Monitor blood counts"],
          manufacturer: "Lupin Ltd",
          expiryDate: "2027-11",
          composition: "Linezolid 600mg",
        },
        {
          id: "med-032",
          name: "Rifaximin",
          brand: "Rifaxin-200",
          category: "Antibiotic",
          price: 160,
          originalPrice: 200,
          rating: 4.7,
          reviews: 280,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Non-systemic antibiotic that treats bacterial diarrhea without entering blood stream.",
          uses: ["Pet Ka Infection", "Traveler's Diarrhea", "IBS"],
          dosage: "1 tablet three times daily for 3 days",
          sideEffects: ["Flatulence", "Headache", "Abdominal pain"],
          warnings: ["Only for non-invasive/non-bloody diarrhea", "Consult doctor if fever occurs"],
          manufacturer: "Sun Pharma",
          expiryDate: "2027-10",
          composition: "Rifaximin 200mg",
        },
        {
          id: "med-033",
          name: "Cefpodoxime Proxetil",
          brand: "Podowal-100 DT",
          category: "Antibiotic",
          price: 115,
          originalPrice: 145,
          rating: 4.6,
          reviews: 190,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Dispersible antibiotic tablets suitable for respiratory, throat, and urinary infections.",
          uses: ["Throat & Ear Infections", "Urinary Tract Infections"],
          dosage: "1 tablet twice daily as prescribed",
          sideEffects: ["Diarrhea", "Nausea", "Headache"],
          warnings: ["Can dissolve in water before consuming", "Complete the full course"],
          manufacturer: "Macleods Pharmaceuticals",
          expiryDate: "2027-09",
          composition: "Cefpodoxime Proxetil 100mg",
        },
        {
          id: "med-034",
          name: "Ofloxacin & Ornidazole",
          brand: "Oflowal-OZ",
          category: "Antibiotic",
          price: 95,
          originalPrice: 125,
          rating: 4.8,
          reviews: 980,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Highly effective dual antibiotic for bacterial and amoebic diarrhea and dysentery.",
          uses: ["Loose Motions / Dast", "Dysentery", "Stomach Infections"],
          dosage: "1 tablet twice daily for 5 days as prescribed",
          sideEffects: ["Nausea", "Metallic taste", "Loss of appetite"],
          warnings: ["Do not consume alcohol", "Complete the full course"],
          manufacturer: "Wallace Pharmaceuticals",
          expiryDate: "2027-08",
          composition: "Ofloxacin 200mg + Ornidazole 500mg",
        },
        {
          id: "med-035",
          name: "Azithromycin",
          brand: "Azce-500",
          category: "Antibiotic",
          price: 120,
          originalPrice: 150,
          rating: 4.7,
          reviews: 1150,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Common 3-day course antibiotic for respiratory, throat, and skin bacterial infections.",
          uses: ["Sore Throat", "Tonsillitis", "Dry Cough"],
          dosage: "1 tablet daily for 3 days on empty stomach",
          sideEffects: ["Nausea", "Diarrhea", "Vomiting"],
          warnings: ["Take 1 hour before or 2 hours after meals", "Complete course"],
          manufacturer: "Apex Laboratories",
          expiryDate: "2027-07",
          composition: "Azithromycin 500mg",
        },
        {
          id: "med-036",
          name: "Amoxicillin & Clavulanate",
          brand: "Walamox CV-625",
          category: "Antibiotic",
          price: 200,
          originalPrice: 250,
          rating: 4.8,
          reviews: 1340,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Powerful penicillin antibiotic combination to treat bacterial infections resistant to amoxicillin.",
          uses: ["Wound Healing", "Sinus Infections", "Chest Infections"],
          dosage: "1 tablet twice daily after meals",
          sideEffects: ["Diarrhea", "Nausea", "Thrush (candidiasis)"],
          warnings: ["Do not take if allergic to Penicillin", "Drink plenty of water"],
          manufacturer: "Wallace Pharmaceuticals",
          expiryDate: "2027-06",
          composition: "Amoxicillin 500mg + Clavulanic Acid 125mg",
        },
        {
          id: "med-037",
          name: "Rifampicin & Isoniazid",
          brand: "R-Cinex kid",
          category: "Antibiotic",
          price: 65,
          originalPrice: 80,
          rating: 4.6,
          reviews: 95,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Combination antitubercular medicine designed specifically for children.",
          uses: ["Childhood TB Treatment"],
          dosage: "As directed by child specialist",
          sideEffects: ["Orange/Red colored urine (harmless)", "Liver enzyme elevation"],
          warnings: ["Monitor liver enzymes", "Administer regularly without fail"],
          manufacturer: "Lupin Ltd",
          expiryDate: "2027-05",
          composition: "Rifampicin 100mg + Isoniazid 50mg",
        },
        {
          id: "med-038",
          name: "Rifampicin, Isoniazid & Pyrazinamide",
          brand: "Macex-ZM",
          category: "Antibiotic",
          price: 195,
          originalPrice: 250,
          rating: 4.7,
          reviews: 120,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Standard triple drug combination treatment for active pulmonary tuberculosis.",
          uses: ["Active Tuberculosis (TB)"],
          dosage: "As directed by TB specialist",
          sideEffects: ["Red colored urine (normal)", "Joint pain", "Nausea"],
          warnings: ["Avoid alcohol completely", "Regular liver function tests mandatory"],
          manufacturer: "Macleods Pharmaceuticals",
          expiryDate: "2027-04",
          composition: "Rifampicin 225mg + Isoniazid 150mg + Pyrazinamide 750mg",
        },
        {
          id: "med-039",
          name: "Metronidazole",
          brand: "Flagyl-400",
          category: "Acidity",
          price: 22,
          originalPrice: 28,
          rating: 4.5,
          reviews: 860,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Amoebicide and antibiotic used to treat stomach infections, amoebic dysentery and loose motions.",
          uses: ["Loose Motions", "Pet Ki Aithan", "Amoebiasis"],
          dosage: "1 tablet three times daily after food",
          sideEffects: ["Metallic taste", "Nausea", "Headache"],
          warnings: ["Strictly avoid alcohol during and 3 days after treatment"],
          manufacturer: "Abbott India",
          expiryDate: "2027-03",
          composition: "Metronidazole 400mg",
        },
        {
          id: "med-040",
          name: "Doxycycline & Lactic Acid Bacillus",
          brand: "Doxyace-LB",
          category: "Antibiotic",
          price: 85,
          originalPrice: 110,
          rating: 4.6,
          reviews: 320,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Antibiotic frequently used for acne treatment, with added stomach safety to prevent gastritis.",
          uses: ["Bacterial Infections", "Acne & Pimples"],
          dosage: "1 tablet twice daily after meals",
          sideEffects: ["Nausea", "Sensitivity to light", "Esophageal irritation"],
          warnings: ["Do not lie down immediately after taking", "Take with plenty of water"],
          manufacturer: "Alkem Laboratories Ltd",
          expiryDate: "2027-02",
          composition: "Doxycycline 100mg + Lactic Acid Bacillus 60M Spores",
        },
        {
          id: "med-041",
          name: "Rabeprazole Sodium",
          brand: "Cyra-20",
          category: "Acidity",
          price: 85,
          originalPrice: 110,
          rating: 4.8,
          reviews: 510,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/omez.png",
          description: "Proton pump inhibitor that reduces acid production in the stomach for heartburn relief.",
          uses: ["Stomach Acidity", "Heartburn", "Acid Reflux"],
          dosage: "1 tablet daily on empty stomach in the morning",
          sideEffects: ["Headache", "Flatulence", "Stomach ache"],
          warnings: ["Take 30 mins before breakfast"],
          manufacturer: "Systopic Laboratories",
          expiryDate: "2027-01",
          composition: "Rabeprazole Sodium 20mg",
        },
        {
          id: "med-042",
          name: "Bisacodyl",
          brand: "Dulcoflex",
          category: "Acidity",
          price: 12,
          originalPrice: 15,
          rating: 4.7,
          reviews: 1100,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/tablets_blister.png",
          description: "Stimulant laxative that relieves occasional constipation.",
          uses: ["Constipation Relief", "Bowel Clearance"],
          dosage: "1-2 tablets at bedtime",
          sideEffects: ["Abdominal cramps", "Diarrhea", "Dehydration"],
          warnings: ["Do not take daily for more than a week", "Drink plenty of water"],
          manufacturer: "Sanofi India",
          expiryDate: "2026-12",
          composition: "Bisacodyl 5mg",
        },
        {
          id: "med-043",
          name: "Pre & Probiotic",
          brand: "Ebiotic",
          category: "Acidity",
          price: 110,
          originalPrice: 140,
          rating: 4.8,
          reviews: 290,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/capsules_box.png",
          description: "Digestive supplement containing beneficial bacteria to improve gut health and restore digestive balance.",
          uses: ["Digestion Improvement", "Stomach Flora Recovery"],
          dosage: "1 capsule daily after meal",
          sideEffects: ["Mild bloating (rare)"],
          warnings: ["Store in a cool dry place"],
          manufacturer: "USV Ltd",
          expiryDate: "2026-11",
          composition: "Prebiotics & Probiotics Blend",
        },
        {
          id: "med-044",
          name: "Ursodeoxycholic Acid",
          brand: "Movebile-300",
          category: "Cardiovascular",
          price: 350,
          originalPrice: 430,
          rating: 4.7,
          reviews: 150,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Naturally occurring bile acid used to dissolve gallstones and treat chronic liver diseases.",
          uses: ["Gallstones Dissolution", "Liver Function Support"],
          dosage: "1 tablet twice daily with food",
          sideEffects: ["Diarrhea", "Nausea", "Itching"],
          warnings: ["Regular liver tests needed", "Avoid taking with antacids"],
          manufacturer: "Torrent Pharmaceuticals",
          expiryDate: "2026-10",
          composition: "Ursodeoxycholic Acid 300mg",
        },
        {
          id: "med-045",
          name: "Ondansetron",
          brand: "Woniwal-4MD",
          category: "Acidity",
          price: 48,
          originalPrice: 60,
          rating: 4.8,
          reviews: 830,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Fast-melting antiemetic for relief from vomiting, nausea, and motion sickness.",
          uses: ["Nausea Control", "Vomiting Relief"],
          dosage: "1 tablet dissolved on tongue before travel/food",
          sideEffects: ["Headache", "Constipation", "Warmth/Flushing"],
          warnings: ["Keep on tongue, let it dissolve", "Consult doctor if symptom persists"],
          manufacturer: "Wallace Pharmaceuticals",
          expiryDate: "2026-09",
          composition: "Ondansetron 4mg",
        },
        {
          id: "med-046",
          name: "Sodium Picosulphate",
          brand: "Cremawal",
          category: "Acidity",
          price: 95,
          originalPrice: 120,
          rating: 4.6,
          reviews: 320,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/tablets_blister.png",
          description: "Laxative to treat severe constipation and empty the bowel before medical examinations.",
          uses: ["Severe Constipation", "Stomach Cleansing"],
          dosage: "1 tablet at bedtime with plenty of water",
          sideEffects: ["Abdominal pain", "Dehydration", "Diarrhea"],
          warnings: ["Do not use continuously", "Consult doctor if kidney issues exist"],
          manufacturer: "Abbott India",
          expiryDate: "2026-08",
          composition: "Sodium Picosulphate 5mg",
        },
        {
          id: "med-047",
          name: "Omeprazole & Domperidone",
          brand: "Omerwal-D",
          category: "Acidity",
          price: 110,
          originalPrice: 140,
          rating: 4.7,
          reviews: 1420,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/omez.png",
          description: "Relieves heartburn, hyperacidity, acid reflux, and associated nausea/vomiting.",
          uses: ["Hyperacidity", "Acid Reflux Nausea"],
          dosage: "1 capsule in the morning before food",
          sideEffects: ["Headache", "Dry mouth", "Mild stomach pain"],
          warnings: ["Take 30 mins before food"],
          manufacturer: "Micro Labs Ltd",
          expiryDate: "2026-07",
          composition: "Omeprazole 20mg + Domperidone 10mg",
        },
        {
          id: "med-048",
          name: "Ranitidine",
          brand: "Acidoc-300",
          category: "Acidity",
          price: 35,
          originalPrice: 45,
          rating: 4.7,
          reviews: 2340,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/tablets_blister.png",
          description: "H2 receptor antagonist that decreases stomach acid production for ulcer and indigestion relief.",
          uses: ["Stomach Gas", "Indigestion Heartburn"],
          dosage: "1 tablet twice daily (morning & night) before food",
          sideEffects: ["Headache", "Muscle pain", "Constipation"],
          warnings: ["Do not consume heavy spicy foods during treatment"],
          manufacturer: "Cipla Ltd",
          expiryDate: "2026-06",
          composition: "Ranitidine 300mg",
        },
        {
          id: "med-049",
          name: "Drotaverine Hydrochloride",
          brand: "Valdota-DS",
          category: "Pain Relief",
          price: 95,
          originalPrice: 125,
          rating: 4.8,
          reviews: 410,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Spasmolytic used to relieve pain from muscle spasms in abdomen, uterus, or kidneys.",
          uses: ["Stomach Pain", "Abdominal Spasms"],
          dosage: "1 tablet as needed. Max 3 times daily.",
          sideEffects: ["Nausea", "Dry mouth", "Vertigo"],
          warnings: ["Not for patients with severe liver/kidney/heart disorders"],
          manufacturer: "Macleods Pharmaceuticals",
          expiryDate: "2027-12",
          composition: "Drotaverine Hydrochloride 80mg",
        },
        {
          id: "med-050",
          name: "Esomeprazole",
          brand: "Esperzome-40",
          category: "Acidity",
          price: 130,
          originalPrice: 160,
          rating: 4.7,
          reviews: 750,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/omez.png",
          description: "Proton pump inhibitor that manages heartburn, severe acidity, and stomach ulcers.",
          uses: ["Stomach Ulcers", "Severe Acid Reflux"],
          dosage: "1 tablet daily in morning before food",
          sideEffects: ["Headache", "Diarrhea", "Stomach ache"],
          warnings: ["Avoid long-term usage without calcium supplements"],
          manufacturer: "Sun Pharma",
          expiryDate: "2027-11",
          composition: "Esomeprazole 40mg",
        },
        {
          id: "med-051",
          name: "Racecadotril",
          brand: "Zedott",
          category: "Acidity",
          price: 80,
          originalPrice: 100,
          rating: 4.8,
          reviews: 390,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Antidiarrheal drug acting as a peripheral enkephalinase inhibitor to reduce water secretion.",
          uses: ["Acute Diarrhea (Dast)"],
          dosage: "1 capsule three times daily as prescribed",
          sideEffects: ["Headache", "Skin rash (rare)", "Constipation"],
          warnings: ["Stay hydrated with ORS along with this medicine"],
          manufacturer: "Torrent Pharmaceuticals",
          expiryDate: "2027-10",
          composition: "Racecadotril 100mg",
        },
        {
          id: "med-052",
          name: "Cetirizine & Paracetamol",
          brand: "Cetriace Cold",
          category: "Allergy",
          price: 45,
          originalPrice: 55,
          rating: 4.6,
          reviews: 830,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/allegra.png",
          description: "Relieves common cold symptoms like runny nose, sneezing, body ache, and fever.",
          uses: ["Common Cold", "Sneezing & Fever"],
          dosage: "1 tablet at bedtime after food",
          sideEffects: ["Drowsiness", "Dry mouth", "Headache"],
          warnings: ["May cause drowsiness, avoid driving or alcohol"],
          manufacturer: "Alkem Laboratories Ltd",
          expiryDate: "2027-09",
          composition: "Cetirizine Hydrochloride 5mg + Paracetamol 325mg",
        },
        {
          id: "med-053",
          name: "Etophylline & Theophylline",
          brand: "Deriphyllin",
          category: "Allergy",
          price: 35,
          originalPrice: 45,
          rating: 4.7,
          reviews: 1850,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Bronchodilator to relax airways for patients with asthma and chronic breathing difficulties.",
          uses: ["Asthma Relief", "Breathing Difficulties"],
          dosage: "1 tablet twice daily or as prescribed",
          sideEffects: ["Restlessness", "Nausea", "Increased heart rate"],
          warnings: ["Do not crush or chew", "Monitor heart parameters if taking high doses"],
          manufacturer: "Zydus Cadila",
          expiryDate: "2027-08",
          composition: "Etophylline 77mg + Theophylline 23mg",
        },
        {
          id: "med-054",
          name: "Fexofenadine Hydrochloride",
          brand: "Fexocoat 120",
          category: "Allergy",
          price: 110,
          originalPrice: 140,
          rating: 4.8,
          reviews: 620,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/allegra.png",
          description: "Non-drowsy antihistamine for quick relief of allergic rhinitis, sneezing, and skin itching.",
          uses: ["Skin Allergy", "Sneezing & Runny Nose"],
          dosage: "1 tablet daily in the morning",
          sideEffects: ["Headache", "Drowsiness (rare)", "Nausea"],
          warnings: ["Do not take with fruit juice", "Not for children under 12"],
          manufacturer: "Apex Laboratories",
          expiryDate: "2027-07",
          composition: "Fexofenadine Hydrochloride 120mg",
        },
        {
          id: "med-055",
          name: "Methylprednisolone",
          brand: "Methycell-4",
          category: "Allergy",
          price: 45,
          originalPrice: 55,
          rating: 4.6,
          reviews: 210,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Corticosteroid to treat severe allergic reactions, skin conditions, and inflammatory conditions.",
          uses: ["Severe Allergies", "Inflammation Relief"],
          dosage: "1 tablet daily after food as prescribed",
          sideEffects: ["Increased blood sugar", "Stomach irritation", "Sleep problems"],
          warnings: ["Do not stop taking suddenly, taper dose as advised by doctor"],
          manufacturer: "Lupin Ltd",
          expiryDate: "2027-06",
          composition: "Methylprednisolone 4mg",
        },
        {
          id: "med-056",
          name: "Levocetirizine & Montelukast",
          brand: "Walimont-LC",
          category: "Allergy",
          price: 135,
          originalPrice: 170,
          rating: 4.8,
          reviews: 1150,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/allegra.png",
          description: "Effective combination to treat allergic rhinitis, asthma symptoms, and chronic sneezing.",
          uses: ["Chronic Allergy", "Cold & Sneezing"],
          dosage: "1 tablet at bedtime after food",
          sideEffects: ["Drowsiness", "Dry mouth", "Headache"],
          warnings: ["Avoid alcohol", "May cause drowsiness"],
          manufacturer: "Wallace Pharmaceuticals",
          expiryDate: "2027-05",
          composition: "Levocetirizine Hydrochloride 5mg + Montelukast Sodium 10mg",
        },
        {
          id: "med-057",
          name: "Deflazacort",
          brand: "Deflawal",
          category: "Allergy",
          price: 120,
          originalPrice: 150,
          rating: 4.5,
          reviews: 140,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Glucocorticoid steroid to decrease inflammation and suppress immune system response during lung infection.",
          uses: ["Lung Swelling", "Severe Allergies"],
          dosage: "1 tablet daily as prescribed",
          sideEffects: ["Weight gain", "Increased appetite", "Increased blood pressure"],
          warnings: ["Regularly check blood pressure", "May mask signs of infection"],
          manufacturer: "Aristo Pharmaceuticals",
          expiryDate: "2027-04",
          composition: "Deflazacort 6mg",
        },
        {
          id: "med-058",
          name: "Pheniramine Maleate",
          brand: "Avid-25",
          category: "Allergy",
          price: 15,
          originalPrice: 20,
          rating: 4.7,
          reviews: 2400,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/tablets_blister.png",
          description: "Antihistamine providing relief from allergic skin conditions, itching, sneezing, and insect bites.",
          uses: ["Skin Itching", "Allergy Relief"],
          dosage: "1 tablet twice daily after meals",
          sideEffects: ["Drowsiness", "Blurred vision", "Dry mouth"],
          warnings: ["Strong sedative action, avoid driving or operating machinery"],
          manufacturer: "Sanofi India",
          expiryDate: "2027-03",
          composition: "Pheniramine Maleate 25mg",
        },
        {
          id: "med-059",
          name: "Gabapentin & Nortriptyline",
          brand: "Gabawal-NT",
          category: "Pain Relief",
          price: 280,
          originalPrice: 350,
          rating: 4.8,
          reviews: 290,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Prescribed for nerve pain (neuropathic pain), shingles, and diabetic neuropathy.",
          uses: ["Chronic Nerve Pain", "Neuropathy"],
          dosage: "1 tablet at bedtime as prescribed",
          sideEffects: ["Drowsiness", "Dry mouth", "Constipation", "Dizziness"],
          warnings: ["Do not discontinue abruptly, can cause withdrawal symptoms"],
          manufacturer: "Sun Pharma",
          expiryDate: "2027-02",
          composition: "Gabapentin 400mg + Nortriptyline Hydrochloride 10mg",
        },
        {
          id: "med-060",
          name: "Clonazepam",
          brand: "Nupam-MD",
          category: "Pain Relief",
          price: 45,
          originalPrice: 60,
          rating: 4.7,
          reviews: 510,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Benzodiazepine used to control seizures, panic disorder, and severe anxiety.",
          uses: ["Anxiety Control", "Seizure Prevention"],
          dosage: "1 tablet dissolved on tongue under supervision",
          sideEffects: ["Drowsiness", "Unsteady walk", "Mood swings"],
          warnings: ["Habit-forming medication, use strictly under doctor's guidance"],
          manufacturer: "Torrent Pharmaceuticals",
          expiryDate: "2027-01",
          composition: "Clonazepam 0.5mg (Mouth Dissolving)",
        },
        {
          id: "med-061",
          name: "Flunarizine & Propranolol",
          brand: "Migorarest",
          category: "Cardiovascular",
          price: 130,
          originalPrice: 165,
          rating: 4.8,
          reviews: 340,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Prevents migraine attacks and reduces the frequency and severity of headaches.",
          uses: ["Migraine Attacks Prevention"],
          dosage: "1 tablet at bedtime",
          sideEffects: ["Weight gain", "Drowsiness", "Slow heart rate"],
          warnings: ["Avoid in patients with asthma or depression"],
          manufacturer: "Lupin Ltd",
          expiryDate: "2027-12",
          composition: "Flunarizine 5mg + Propranolol Hydrochloride 40mg",
        },
        {
          id: "med-062",
          name: "Clonazepam & Propranolol",
          brand: "Wudep",
          category: "Cardiovascular",
          price: 95,
          originalPrice: 120,
          rating: 4.7,
          reviews: 410,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Treats panic disorder, anxiety, palpitations and chest tremors.",
          uses: ["Panic & Palpitations"],
          dosage: "1 tablet daily as prescribed",
          sideEffects: ["Slow heart rate", "Sleepiness", "Dry mouth"],
          warnings: ["Avoid alcohol", "Do not stop suddenly"],
          manufacturer: "Cipla Ltd",
          expiryDate: "2027-11",
          composition: "Clonazepam 0.25mg + Propranolol Hydrochloride 20mg",
        },
        {
          id: "med-063",
          name: "Levetiracetam",
          brand: "Leveace-500",
          category: "Pain Relief",
          price: 140,
          originalPrice: 180,
          rating: 4.8,
          reviews: 290,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Antiepileptic drug used to treat seizures (epilepsy).",
          uses: ["Epilepsy & Seizures"],
          dosage: "1 tablet twice daily as prescribed",
          sideEffects: ["Sleepiness", "Weakness", "Irritability"],
          warnings: ["Do not skip doses", "Regular medical checkups recommended"],
          manufacturer: "Alkem Laboratories Ltd",
          expiryDate: "2027-10",
          composition: "Levetiracetam 500mg",
        },
        {
          id: "med-064",
          name: "Carbamazepine",
          brand: "Zep-CR-200",
          category: "Pain Relief",
          price: 32,
          originalPrice: 40,
          rating: 4.6,
          reviews: 390,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Anticonvulsant to treat epilepsy and neuropathic pain like trigeminal neuralgia.",
          uses: ["Seizures Treatment", "Trigeminal Neuralgia"],
          dosage: "1 tablet once or twice daily as prescribed",
          sideEffects: ["Dizziness", "Nausea", "Skin rashes"],
          warnings: ["Frequent blood counts and liver tests required", "Report rashes immediately"],
          manufacturer: "Torrent Pharmaceuticals",
          expiryDate: "2027-09",
          composition: "Carbamazepine 200mg (Controlled Release)",
        },
        {
          id: "med-065",
          name: "Chlordiazepoxide & Trifluoperazine",
          brand: "Restab",
          category: "Pain Relief",
          price: 55,
          originalPrice: 70,
          rating: 4.5,
          reviews: 110,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Symptomatic relief of mental tension, restlessness, and severe anxiety.",
          uses: ["Mental Tension", "Severe Anxiety"],
          dosage: "1 tablet daily at bedtime",
          sideEffects: ["Drowsiness", "Dry mouth", "Muscle weakness"],
          warnings: ["Can cause dependency", "Avoid driving"],
          manufacturer: "Abbott India",
          expiryDate: "2027-08",
          composition: "Chlordiazepoxide 10mg + Trifluoperazine 1mg",
        },
        {
          id: "med-066",
          name: "Haloperidol",
          brand: "Serenace",
          category: "Pain Relief",
          price: 28,
          originalPrice: 35,
          rating: 4.6,
          reviews: 180,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Antipsychotic medication used to treat schizophrenia, delusions and manic episodes.",
          uses: ["Mental Disorders", "Delusions"],
          dosage: "1 tablet daily as prescribed",
          sideEffects: ["Muscle stiffness", "Tremors", "Restlessness"],
          warnings: ["Regular assessment of movements required", "Consult doctor if stiffness occurs"],
          manufacturer: "RPG Life Sciences",
          expiryDate: "2027-07",
          composition: "Haloperidol 5mg",
        },
        {
          id: "med-067",
          name: "Clonazepam 0.5mg",
          brand: "Nupam-0.5",
          category: "Pain Relief",
          price: 35,
          originalPrice: 45,
          rating: 4.7,
          reviews: 290,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Sedative and muscle relaxant used for sleep disorders, insomnia, and panic attacks.",
          uses: ["Insomnia", "Panic Attacks"],
          dosage: "1 tablet at bedtime as prescribed",
          sideEffects: ["Drowsiness", "Fatigue", "Dizziness"],
          warnings: ["Use strictly as advised", "Do not mix with sleeping aids or alcohol"],
          manufacturer: "Torrent Pharmaceuticals",
          expiryDate: "2027-06",
          composition: "Clonazepam 0.5mg",
        },
        {
          id: "med-068",
          name: "Flupentixol & Melitracen",
          brand: "Placida",
          category: "Pain Relief",
          price: 110,
          originalPrice: 140,
          rating: 4.8,
          reviews: 630,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Combines antidepressant and neuroleptic for mild-to-moderate depression and anxiety.",
          uses: ["Depression & Anxiety"],
          dosage: "1 tablet twice daily as prescribed",
          sideEffects: ["Dry mouth", "Restlessness", "Dizziness"],
          warnings: ["Do not use if recovering from a heart attack"],
          manufacturer: "Lundbeck",
          expiryDate: "2027-05",
          composition: "Flupentixol 0.5mg + Melitracen 10mg",
        },
        {
          id: "med-069",
          name: "Duloxetine",
          brand: "Deawin-20",
          category: "Pain Relief",
          price: 98,
          originalPrice: 125,
          rating: 4.7,
          reviews: 220,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "SNRI used to treat depression, generalized anxiety disorder, and chronic nerve pain.",
          uses: ["Depression", "Chronic Nerve Pain"],
          dosage: "1 tablet once daily as prescribed",
          sideEffects: ["Nausea", "Dry mouth", "Sleepiness"],
          warnings: ["Do not take with MAO inhibitors", "May take 2-4 weeks to show effect"],
          manufacturer: "Sun Pharma",
          expiryDate: "2027-04",
          composition: "Duloxetine Hydrochloride 20mg",
        },
        {
          id: "med-070",
          name: "Chlordiazepoxide & Amitriptyline",
          brand: "Nupox-Forte",
          category: "Pain Relief",
          price: 75,
          originalPrice: 95,
          rating: 4.6,
          reviews: 340,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Indicated for anxiety-associated depression, severe mental tension, and mood disorders.",
          uses: ["Anxiety-Depression", "Mental Peace"],
          dosage: "1 tablet daily at bedtime",
          sideEffects: ["Drowsiness", "Constipation", "Dry mouth"],
          warnings: ["Regular liver and heart monitoring is recommended"],
          manufacturer: "USV Ltd",
          expiryDate: "2027-03",
          composition: "Chlordiazepoxide 10mg + Amitriptyline 25mg",
        },
        {
          id: "med-071",
          name: "L-Carnitine & B-Vitamins",
          brand: "Carnifast",
          category: "Vitamins",
          price: 280,
          originalPrice: 350,
          rating: 4.8,
          reviews: 410,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/green_box.png",
          description: "Amino acid and vitamin supplement to enhance cellular energy, muscle health, and nerve strength.",
          uses: ["Physical Weakness", "Nerve Strength"],
          dosage: "1 tablet daily after meals",
          sideEffects: ["Mild stomach upset (rare)"],
          warnings: ["Consult doctor if you have thyroid issues"],
          manufacturer: "Alkem Laboratories Ltd",
          expiryDate: "2027-02",
          composition: "L-Carnitine L-Tartrate + B-Complex Vitamins",
        },
        {
          id: "med-072",
          name: "Vitamin E",
          brand: "Virala Red",
          category: "Vitamins",
          price: 65,
          originalPrice: 80,
          rating: 4.7,
          reviews: 1890,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/green_box.png",
          description: "Antioxidant support to nourish and protect skin and promote hair health.",
          uses: ["Skin Care", "Hair Growth & Health"],
          dosage: "1 capsule daily after food",
          sideEffects: ["None under normal dosage"],
          warnings: ["Do not exceed recommended daily allowance"],
          manufacturer: "Apex Laboratories",
          expiryDate: "2027-01",
          composition: "Tocopheryl Acetate (Vitamin E) 400IU",
        },
        {
          id: "med-073",
          name: "Vitamin B-Complex with B12",
          brand: "Neurobion Forte",
          category: "Vitamins",
          price: 38,
          originalPrice: 50,
          rating: 4.9,
          reviews: 5200,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/supradyn.png",
          description: "Standard supplement to treat Vitamin B deficiency, neuropathy, and relieve nerve pain.",
          uses: ["Nerve Weakness", "Vitamin B Deficiency"],
          dosage: "1 tablet daily after meals",
          sideEffects: ["None", "Harmless yellow discoloration of urine"],
          warnings: ["Keep out of reach of children"],
          manufacturer: "Procter & Gamble Health",
          expiryDate: "2027-12",
          composition: "Vitamin B1 + B2 + B3 + B5 + B6 + B12",
        },
        {
          id: "med-074",
          name: "Lactic acid Bacillus & Vitamins",
          brand: "Cyno Cal-16",
          category: "Vitamins",
          price: 120,
          originalPrice: 150,
          rating: 4.8,
          reviews: 670,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/green_box.png",
          description: "Lactic acid bacillus combination with essential vitamins to recover stomach gut flora and improve digestion.",
          uses: ["Weakness", "Digestive Support"],
          dosage: "1 capsule twice daily",
          sideEffects: ["None"],
          warnings: ["Keep in dry place"],
          manufacturer: "Sanofi India",
          expiryDate: "2027-11",
          composition: "Lactic Acid Bacillus + Folic Acid + Vitamin B12",
        },
        {
          id: "med-075",
          name: "L-Arginine, Lycopene & Vitamins",
          brand: "LyGwal-RED",
          category: "Vitamins",
          price: 230,
          originalPrice: 290,
          rating: 4.8,
          reviews: 320,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/green_box.png",
          description: "Antioxidant formulation for physical strength, cardiovascular health and immune support.",
          uses: ["Physical Strength", "Antioxidant Support"],
          dosage: "1 capsule daily after breakfast",
          sideEffects: ["Mild stomach bloating"],
          warnings: ["Not a replacement for a balanced diet"],
          manufacturer: "Wallace Pharmaceuticals",
          expiryDate: "2027-10",
          composition: "L-Arginine + Lycopene + Selenium + Vitamins",
        },
        {
          id: "med-076",
          name: "Calcium & Vitamin D3",
          brand: "Aristocal 500",
          category: "Vitamins",
          price: 85,
          originalPrice: 110,
          rating: 4.7,
          reviews: 1450,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/sund3.png",
          description: "Supports bone density, joint health, and improves calcium absorption in the body.",
          uses: ["Bone Strength", "Joint Pain Relief"],
          dosage: "1 tablet daily after food, preferably dinner",
          sideEffects: ["Constipation (mild)"],
          warnings: ["Consult doctor if you have kidney stones history"],
          manufacturer: "Aristo Pharmaceuticals",
          expiryDate: "2027-09",
          composition: "Calcium Carbonate 500mg + Vitamin D3 250IU",
        },
        {
          id: "med-077",
          name: "Carica Papaya Leaf Extract",
          brand: "Carivent",
          category: "Vitamins",
          price: 320,
          originalPrice: 399,
          rating: 4.8,
          reviews: 830,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/green_box.png",
          description: "Natural papaya leaf extract clinically shown to boost platelet count during Dengue fever.",
          uses: ["Boosting Platelet Count", "Dengue Recovery"],
          dosage: "1 tablet three times daily during fever as prescribed",
          sideEffects: ["Nausea", "Mild stomach ache"],
          warnings: ["Always consult a doctor during acute high fever"],
          manufacturer: "Micro Labs Ltd",
          expiryDate: "2027-08",
          composition: "Carica Papaya Leaf Extract 1100mg",
        },
        {
          id: "med-078",
          name: "Liver Capsule",
          brand: "Livayur-Ds",
          category: "Acidity",
          price: 150,
          originalPrice: 190,
          rating: 4.7,
          reviews: 980,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/green_box.png",
          description: "Ayurvedic liver protection capsules designed to stimulate liver enzymes and enhance digestion.",
          uses: ["Liver Protection", "Improving Digestion"],
          dosage: "1 capsule twice daily before meals",
          sideEffects: ["None reported"],
          warnings: ["Contains herbal extracts, do not exceed dosage"],
          manufacturer: "Arya Vaidya Pharmacy",
          expiryDate: "2027-07",
          composition: "Herbal Liver Extract",
        },
        {
          id: "med-079",
          name: "Hyoscine Butylbromide",
          brand: "Buscagast",
          category: "Pain Relief",
          price: 42,
          originalPrice: 55,
          rating: 4.8,
          reviews: 940,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Antispasmodic to relieve severe cramping abdominal pain, renal colic, and spasms.",
          uses: ["Stomach Cramps", "Intestinal Spasms"],
          dosage: "1 tablet as needed. Max 4 times daily.",
          sideEffects: ["Dry mouth", "Mild heart palpitations", "Dizziness"],
          warnings: ["Avoid if you have glaucoma or prostate enlargement"],
          manufacturer: "Boehringer Ingelheim",
          expiryDate: "2027-06",
          composition: "Hyoscine Butylbromide 10mg",
        },
        {
          id: "med-080",
          name: "Calcium Dobesilate",
          brand: "Paraxin",
          category: "Cardiovascular",
          price: 180,
          originalPrice: 230,
          rating: 4.6,
          reviews: 220,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Vasoprotective used to treat chronic venous insufficiency, leg edema, and hemorrhoids (piles).",
          uses: ["Piles (Bawasir)", "Nerve Venous Swelling"],
          dosage: "1 tablet twice daily as prescribed",
          sideEffects: ["Stomach upset", "Fever", "Headache"],
          warnings: ["Monitor kidney functions in elderly patients"],
          manufacturer: "Abbott India",
          expiryDate: "2027-05",
          composition: "Calcium Dobesilate 500mg",
        },
        {
          id: "med-081",
          name: "Xantinol Nicotinate",
          brand: "Complamina",
          category: "Cardiovascular",
          price: 95,
          originalPrice: 120,
          rating: 4.7,
          reviews: 190,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Peripheral vasodilator to improve blood circulation and oxygen supply in nerves and limbs.",
          uses: ["Blood Circulation in Nerves"],
          dosage: "1 tablet twice daily as prescribed",
          sideEffects: ["Flushing", "Warm sensation", "Nausea"],
          warnings: ["Skin flushing is harmless and transient", "Avoid taking on empty stomach"],
          manufacturer: "Abbott India",
          expiryDate: "2027-04",
          composition: "Xantinol Nicotinate 150mg",
        },
        {
          id: "med-082",
          name: "Flavoxate Hydrochloride",
          brand: "Flavowal-200",
          category: "Pain Relief",
          price: 125,
          originalPrice: 160,
          rating: 4.8,
          reviews: 310,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Urinary antispasmodic to reduce pain, frequency, and burning sensation during urination.",
          uses: ["Urinary Pain Relief", "Burning Urination"],
          dosage: "1 tablet three times daily as prescribed",
          sideEffects: ["Dry mouth", "Sleepiness", "Nausea"],
          warnings: ["Avoid driving", "Consult doctor if severe abdominal pain occurs"],
          manufacturer: "Wallace Pharmaceuticals",
          expiryDate: "2027-03",
          composition: "Flavoxate Hydrochloride 200mg",
        },
        {
          id: "med-083",
          name: "Diethylcarbamazine Citrate",
          brand: "Hetrazan",
          category: "Antibiotic",
          price: 35,
          originalPrice: 45,
          rating: 4.7,
          reviews: 680,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Anthelminthic drug used for treating filariasis (elephantiasis) and worm infections.",
          uses: ["Filaria Treatment (Hathipaon)"],
          dosage: "1 tablet three times daily for 12 days as prescribed",
          sideEffects: ["Headache", "Fever", "Nausea", "Drowsiness"],
          warnings: ["Strict compliance is required to completely kill microfilariae"],
          manufacturer: "Pfizer Ltd",
          expiryDate: "2027-02",
          composition: "Diethylcarbamazine Citrate 100mg",
        },
        {
          id: "med-084",
          name: "Tranexamic Acid & Etamsylate",
          brand: "Tranex-EM",
          category: "Cardiovascular",
          price: 290,
          originalPrice: 360,
          rating: 4.9,
          reviews: 290,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Hemostatic combination to stop excessive blood loss during heavy bleeding or surgery.",
          uses: ["Heavy Bleeding Control"],
          dosage: "1 tablet three times daily till bleeding stops as prescribed",
          sideEffects: ["Nausea", "Diarrhea", "Thrombosis (extremely rare)"],
          warnings: ["Do not use if you have history of deep vein thrombosis"],
          manufacturer: "Lupin Ltd",
          expiryDate: "2027-01",
          composition: "Tranexamic Acid 500mg + Etamsylate 250mg",
        },
        {
          id: "med-085",
          name: "Torsemide",
          brand: "Torsewal-10",
          category: "Cardiovascular",
          price: 25,
          originalPrice: 32,
          rating: 4.7,
          reviews: 390,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Diuretic used to reduce fluid swelling (edema) caused by heart, kidney, or liver disease.",
          uses: ["Fluid Swelling (Edema) Reduction"],
          dosage: "1 tablet daily in the morning",
          sideEffects: ["Dehydration", "Lower potassium levels", "Dizziness"],
          warnings: ["Monitor serum electrolytes regularly", "Take in the morning"],
          manufacturer: "Wallace Pharmaceuticals",
          expiryDate: "2027-12",
          composition: "Torsemide 10mg",
        },
        {
          id: "med-086",
          name: "Neeri (Ayurvedic)",
          brand: "Neeri",
          category: "Vitamins",
          price: 135,
          originalPrice: 170,
          rating: 4.8,
          reviews: 2100,
          inStock: true,
          prescriptionRequired: false,
          image: "/medicines/green_box.png",
          description: "Herbal formula for renal health, helping flush out kidney stones and treat urinary tract infections.",
          uses: ["Kidney Stones", "Urinary Tract Infections"],
          dosage: "2 tablets twice daily",
          sideEffects: ["None reported"],
          warnings: ["Drink at least 3-4 liters of water daily while taking"],
          manufacturer: "Aimil Pharmaceuticals",
          expiryDate: "2027-11",
          composition: "Ayurvedic Renal Herbs",
        },
        {
          id: "med-087",
          name: "Doxylamine & Pyridoxine",
          brand: "Pandoxin",
          category: "Acidity",
          price: 85,
          originalPrice: 110,
          rating: 4.7,
          reviews: 830,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Combines antihistamine and Vitamin B6 to prevent morning sickness and nausea during pregnancy.",
          uses: ["Pregnancy Nausea & Vomiting"],
          dosage: "1-2 tablets at bedtime as prescribed",
          sideEffects: ["Sleepiness", "Dry mouth", "Constipation"],
          warnings: ["May cause severe drowsiness", "Do not take on empty stomach"],
          manufacturer: "Apex Laboratories",
          expiryDate: "2027-10",
          composition: "Doxylamine Succinate 10mg + Pyridoxine Hydrochloride (Vit B6) 10mg",
        },
        {
          id: "med-088",
          name: "Methylergometrine Maleate",
          brand: "Methygeve",
          category: "Cardiovascular",
          price: 75,
          originalPrice: 95,
          rating: 4.8,
          reviews: 320,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/blue_box.png",
          description: "Prevents and controls postpartum hemorrhage (excessive bleeding after childbirth).",
          uses: ["Post-delivery Bleeding Prevention"],
          dosage: "1 tablet three times daily as prescribed",
          sideEffects: ["Nausea", "Increased blood pressure", "Headache"],
          warnings: ["Highly contraindicated in pregnancy, only for postpartum use"],
          manufacturer: "Macleods Pharmaceuticals",
          expiryDate: "2027-09",
          composition: "Methylergometrine Maleate 0.125mg",
        },
        {
          id: "med-089",
          name: "Cinnarizine & Domperidone",
          brand: "Gingeron-D",
          category: "Acidity",
          price: 65,
          originalPrice: 80,
          rating: 4.6,
          reviews: 290,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/tablets_blister.png",
          description: "Relieves motion sickness, vertigo (chakkar), dizziness, and vomiting symptoms.",
          uses: ["Vertigo (Chakkar) & Vomiting"],
          dosage: "1 tablet twice daily before food",
          sideEffects: ["Sleepiness", "Dry mouth", "Indigestion"],
          warnings: ["May cause drowsiness, do not drink alcohol"],
          manufacturer: "Alkem Laboratories Ltd",
          expiryDate: "2027-08",
          composition: "Cinnarizine 20mg + Domperidone 15mg",
        },
        {
          id: "med-090",
          name: "Cefixime & Citicoline",
          brand: "Neurocare",
          category: "Antibiotic",
          price: 350,
          originalPrice: 430,
          rating: 4.8,
          reviews: 110,
          inStock: true,
          prescriptionRequired: true,
          image: "/medicines/capsules_box.png",
          description: "Premium combination drug to treat bacterial infection and promote brain cell recovery.",
          uses: ["Brain Recovery & Infection Treatment"],
          dosage: "1 tablet twice daily as prescribed",
          sideEffects: ["Stomach upset", "Diarrhea", "Headache"],
          warnings: ["Complete full course", "Not for minor infections"],
          manufacturer: "Micro Labs Ltd",
          expiryDate: "2027-07",
          composition: "Cefixime 200mg + Citicoline 500mg",
        },
      ],

      addMedicine: (med) => {
        const id = `med-0${Math.floor(91 + Math.random() * 900)}`;
        const newMed: Medicine = {
          ...med,
          id,
          rating: 4.5,
          reviews: 1,
        };
        set((state) => ({ medicines: [newMed, ...state.medicines] }));
      },

      toggleStock: (id) => {
        set((state) => ({
          medicines: state.medicines.map((m) =>
            m.id === id ? { ...m, inStock: !m.inStock } : m
          ),
        }));
      },

      removeMedicine: (id) => {
        set((state) => ({
          medicines: state.medicines.filter((m) => m.id !== id),
        }));
      },

      clearAll: () => set({ medicines: [] }),
    }),
    { name: "medimind-medicines" }
  )
);
